network:
  version: 2
  ethernets:
    eth0:
      dhcp4: no
      addresses:
        - 192.168.1.1/24
    eth1:
      dhcp4: no
      addresses:
        - 10.0.0.2/24
      nameservers:
        addresses:
          - 8.8.8.8
      routes:
        - to: 0.0.0.0/0
          via: 10.0.0.1